"""add agent_run, position_snapshot, portfolio_snapshot, review, cost_ledger

Revision ID: 03bc1183d4b5
Revises: 7185387df564
Create Date: 2026-07-04 23:52:19.548546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03bc1183d4b5'
down_revision: Union[str, Sequence[str], None] = '7185387df564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('scope', sa.Enum('SYSTEM', 'PERSONA', name='cost_ledger_scope'), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=True),
    sa.Column('agent', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCEEDED', 'FAILED', name='agent_run_status'), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycle.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_snapshot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cash', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('pnl_realized', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('pnl_unrealized', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('benchmark_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position_snapshot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('instrument', sa.String(length=20), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('pnl_unrealized', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=False),
    sa.Column('expected', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actual', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deviation', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('slippage_malus', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('verdict', sa.Enum('THESIS_CONFIRMED', 'THESIS_FAILED', 'INCONCLUSIVE', name='review_verdict'), nullable=False),
    sa.Column('lessons_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('position_snapshot')
    op.drop_table('portfolio_snapshot')
    op.drop_table('agent_run')
    op.drop_table('cost_ledger')
    # ### end Alembic commands ###
    # Postgres ENUM types survive DROP TABLE — see revision 7185387df564 for why
    # this is needed (upgrade/downgrade/upgrade cycle test, F003 §3 test 1).
    sa.Enum(name='review_verdict').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='agent_run_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='cost_ledger_scope').drop(op.get_bind(), checkfirst=True)
