"""initial schema: persona, portfolio, cycle, research_item, decision, order_record

Revision ID: 7185387df564
Revises: 
Create Date: 2026-07-04 23:38:33.270522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7185387df564'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycle',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trading_day', sa.Date(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('market_session', sa.Enum('US_EQUITY', 'CRYPTO', name='market_session'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persona',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('charter_version', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('config_ref', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('portfolio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('PAPER', 'LIVE', name='portfolio_mode'), nullable=False),
    sa.Column('broker_account_ref', sa.String(length=100), nullable=False),
    sa.Column('base_ccy', sa.String(length=3), nullable=False),
    sa.Column('start_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('agent', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_ref', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('instruments', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('instrument', sa.String(length=20), nullable=False),
    sa.Column('action', sa.Enum('BUY', 'SELL', 'HOLD', 'CLOSE', 'REJECT_IDEA', name='decision_action'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('thesis_text', sa.Text(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('expected_outcome', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_research_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('risk_check', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hitl', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RISK_REJECTED', 'HITL_PENDING', 'HITL_REJECTED', 'APPROVED', 'EXECUTED', 'RECORDED', name='decision_status'), nullable=False),
    sa.CheckConstraint('array_length(input_research_ids, 1) IS NOT NULL', name='ck_decision_input_research_ids_not_empty'),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycle.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('broker', sa.String(length=50), nullable=False),
    sa.Column('broker_order_id', sa.String(length=100), nullable=True),
    sa.Column('mode', sa.Enum('PAPER', 'LIVE', name='portfolio_mode'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.Column('fill_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('fees', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'FILLED', 'PARTIALLY_FILLED', 'CANCELED', 'REJECTED', 'EXPIRED', name='order_record_status'), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_record')
    op.drop_table('decision')
    op.drop_table('research_item')
    op.drop_table('portfolio')
    op.drop_table('persona')
    op.drop_table('cycle')
    # ### end Alembic commands ###
    # Postgres ENUM types survive DROP TABLE and must be dropped explicitly, or a
    # subsequent upgrade() fails with "type already exists" (found by testing the
    # upgrade/downgrade/upgrade cycle, see F003 §3 test 1).
    sa.Enum(name='decision_action').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='decision_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='order_record_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='market_session').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='portfolio_mode').drop(op.get_bind(), checkfirst=True)
