"""add edgar_filing

Revision ID: 74cd69ad0125
Revises: 71687961eb9f
Create Date: 2026-07-05 22:03:35.457639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74cd69ad0125'
down_revision: Union[str, Sequence[str], None] = '71687961eb9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edgar_filing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('accession_number', sa.String(length=30), nullable=False),
    sa.Column('cik', sa.String(length=20), nullable=True),
    sa.Column('company_name', sa.String(length=300), nullable=False),
    sa.Column('form_type', sa.String(length=20), nullable=False),
    sa.Column('filed_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edgar_filing')
    # ### end Alembic commands ###
