"""add musterdepot_transaction

Revision ID: b8bf07d06546
Revises: f51bad7b1d9a
Create Date: 2026-07-06 20:29:15.726135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8bf07d06546'
down_revision: Union[str, Sequence[str], None] = 'f51bad7b1d9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('musterdepot_transaction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.String(length=300), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('instrument_name', sa.String(length=200), nullable=False),
    sa.Column('wkn', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'seq', name='uq_musterdepot_transaction_message_seq')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('musterdepot_transaction')
    # ### end Alembic commands ###
