"""add aktienfinder_snapshot

Revision ID: f51bad7b1d9a
Revises: b7876aca814a
Create Date: 2026-07-05 22:26:12.209510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f51bad7b1d9a'
down_revision: Union[str, Sequence[str], None] = 'b7876aca814a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aktienfinder_snapshot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('screenshot_path', sa.String(length=500), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'snapshot_date', name='uq_aktienfinder_snapshot_symbol_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aktienfinder_snapshot')
    # ### end Alembic commands ###
